export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS'
export const LOGIN_USER = 'LOGIN_USER'
export const LOGIN_USER_REJECTED = 'LOGIN_USER_REJECTED'

export const FETCH_QUOTES = 'FETCH_QUOTES'
export const FETCH_QUOTES_SUCCESS = 'FETCH_QUOTES_SUCCESS'
export const FETCH_QUOTES_REJECTED = 'FETCH_QUOTES_REJECTED'
export const CREATE_NOTE = 'CREATE_NOTE'
export const CREATE_NOTE_SUCCESS = 'CREATE_NOTE_SUCCESS'
export const CREATE_NOTE_REJECTED = 'CREATE_NOTE_REJECTED'

export const FETCH_SINGLE_QUOTE = 'FETCH_SINGLE_QUOTE'
export const FETCH_SINGLE_QUOTE_SUCCESS = 'FETCH_SINGLE_QUOTE_SUCCESS'

export const SET_QUOTE_ID = 'SET_QUOTE_ID'

export const FETCH_FAVORITES = 'FETCH_FAVORITES'
export const FETCH_FAVORITES_SUCCESS = 'FETCH_FAVORITES_SUCCESS'
export const FETCH_FAVORITES_REJECTED = 'FETCH_FAVORITES_REJECTED'

export const FETCH_COMMENTS = 'FETCH_COMMENTS'
export const FETCH_COMMENTS_SUCCESS = 'FETCH_COMMENTS_SUCCESS'
export const FETCH_COMMENTS_REJECTED = 'FETCH_COMMENTS_REJECTED'

export const FETCH_TOP = 'FETCH_TOP'
export const FETCH_TOP_SUCCESS = 'FETCH_TOP_SUCCESS'
export const FETCH_TOP_REJECTED = 'FETCH_TOP_REJECTED'

export const REMOVE_QUOTES_FROM_ARRAY = 'REMOVE_QUOTES_FROM_ARRAY'
